name: test-check

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
        name: decrypting-action

      - run: make setup
      - run: make lint
      - run: make test

      - name: setup git config
        run: |
          git config user.name "Bot"
          git config user.email "<>"

      - name: Prepare template
        run: |
          git checkout --orphan main source
          echo '' > index.js
          echo '' > .gitattributes # disable encryption
          git add -A
          git commit --no-verify -m "Rebuild template (auto)"
          git push -f --no-verify --set-upstream origin main
